apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: test-web
type: Opaque
stringData:
  DB_NAME: "__DB_NAME__"
  DB_USER: "__DB_USER__"
  DB_PASSWORD: "__DB_PASSWORD__"
  DB_HOST: "__DB_HOST__(rds-endpoint)"
  DB_PORT: "__DB_PORT__"
  DJANGO_SECRET_KEY: "__DJANGO_SECRET_KEY__"
  DJANGO_DEBUG: "__DJANGO_DEBUG__"
  DJANGO_ALLOWED_HOSTS: "__DJANGO_ALLOWED_HOSTS__"